paperwork:
  image: paperwork
  privileged: true
  environment:
    - DISPLAY=:0
    - HOME=/home/paperworker
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /home/karsten/Documents/pwdocker:/home/paperworker

