paperwork:
  image: kschwank/paperwork-docker:unstable
  privileged: true
  environment:
    - DISPLAY=:0
    - HOME=/home/paperworker
  volumes:
    - /dev/bus/usb:/dev/bus/usb
    - /tmp/.X11-unix:/tmp/.X11-unix

